### PR TITLE
-- fix login page styling

### PR DESCRIPTION
**Pull request by abdussamadbello**
Fixed the login style to remain consistent with the registration page

### CODE REVIEW

**Review by AbdullahiAbdulkabir — CHANGES_REQUESTED** [review]
Checking it on both PC and phone view the input section is very small, kindly adjust that to be a little bit wider @abdussamadbello Shukran for your effort.  
image

**Comment by abdussamadbello** [comment]
Increased the size

**Comment by AbdullahiAbdulkabir** [comment]
Awesome, just found out that we don't have any implementation for social login, should we still have it there? @geektutor

**Comment by geektutor** [comment]
I dont think we should have social login in the roadmap. Lean and simple should be the goal. Thoughts @nerdymuslim ?

**Review by geektutor — APPROVED** [review]

**Comment by abdussamadbello** [comment]
It shouldn't be that painfull to implement social login with laravel.

https://laravel.com/docs/7.x/socialite

**Comment by nerdymuslim** [comment]
Please let's add social login. We just might be using Google alone or github

**Review by AbdullahiAbdulkabir — APPROVED** [review]

**Comment by AbdullahiAbdulkabir** [comment]
I am supposed to revert this PR because it doesn't follow the standard contribution guidelines. All PR are meant to be sent against the staging branch, pls take note @abdussamadbello

**Pull request merged**
